### ISSUE TITLE
Introduce a reclaim policy for ephemerally created `Virtual IP` resources

### ISSUE THREAD

**Issue by balpert89** [ironcore-dev/ironcore#1115]
# Summary

Similar to https://github.com/ironcore-dev/ironcore/issues/1114 the same `Reclaim Policy` should be available for `Virtual IP` resources.

## Basic example

```
apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine
spec:
  networkInterfaces:
  - ephemeral:
      networkInterfaceTemplate:
        metadata:
          creationTimestamp: null
        spec:
          ipFamilies:
          - IPv4
          ips:
          - ephemeral:
              prefixTemplate:
                metadata:
                  creationTimestamp: null
                spec:
                  ipFamily: IPv4
                  parentRef:
                    name: prefix
                  prefixLength: 32
          networkRef:
            name: network
          virtualIP:
            reclaimPolicy: Retain # this is the new field defining the "Retain" strategy for the corresponding volume resource
            virtualIPRef:
              name: ip-ref
    name: primary
```

This instructs the controller to not remove the `Virtual IP` resource. When the managing `Machine` / `NetworkInterface` resource is deleted, the OwnerReference as well as the `.spec.targetRef` should be cleared.

## Motivation

Resource saving for consuming teams, such as VPN configuration.

**Comment by Rohit-0505** [comment]
@balpert89, @afritzler, the example for enforcing `ReclaimPolicy` on ephemerally created VirtualIPs should indeed follow a similar approach to how ephemeral volumes handle reclaim policies in #1114 
Here’s a revised example demonstrating how to structure this logic, please confirm if this looks good?
```
apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine
spec:
  networkInterfaces:
  - ephemeral:
      networkInterfaceTemplate:
        metadata:
          creationTimestamp: null
        spec:
          ipFamilies:
          - IPv4
          ips:
          - ephemeral:
              prefixTemplate:
                metadata:
                  creationTimestamp: null
                spec:
                  ipFamily: IPv4
                  parentRef:
                    name: prefix
                  prefixLength: 32
          networkRef:
            name: network
          virtualIP:
             ephemeral:
               virtualIPTemplate:
                 metadata:
                   creationTimestamp: null
                 spec:
                   reclaimPolicy: Retain # this is the new field defining the "Retain" strategy for the corresponding `virtualIP` resource
                   ipFamily: IPv4
                   type: Public
    name: primary
```
