### ISSUE TITLE
The `Machine` status should track a reference for its claimed `NetworkInterface` resource

### ISSUE THREAD

**Issue by balpert89** [ironcore-dev/ironcore#1117]
# Summary

The `Machine` status only has information of the current handle of a `NetworkInterface`. [The `NetworkInterfaceStatus` struct](https://github.com/ironcore-dev/ironcore/blob/main/api/compute/v1alpha1/machine_types.go#L126) should expose a field which unanimously identifies the claimed `NetworkInterface` on API level (a reference to a `networkinterface.networking.ironcore.dev` resource). This should be a of type `corev1.LocalObjectReference`.

## Basic example

```
apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine
  namespace: my-namespace
spec:
  ...
status:
  networkInterfaces:
  - handle: ironcore-net://xyz
    lastStateTransitionTime: "2024-09-04T11:38:24Z"
    name: primary
    networkInterfaceRef:
      name: machine-primary
    state: Attached
```

## Motivation

This is a quality of life addition to easily identify the resources claimed by a `Machine` resource.
