### ISSUE TITLE
The `Machine` status should track a reference for its claimed `Volume` resource

### ISSUE THREAD

**Issue by balpert89** [ironcore-dev/ironcore#1118]
# Summary

The `Machine` status only has information of the current handle of a `Volume`. [The `VolumeStatus` struct](https://github.com/ironcore-dev/ironcore/blob/main/api/compute/v1alpha1/machine_types.go#L152) should expose a field which unanimously identifies the claimed `Volume` on API level (a reference to a `volume.storage.ironcore.dev` resource). This should be a of type `corev1.LocalObjectReference`.

## Basic example

```
apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  name: machine
  namespace: my-namespace
spec:
  ...
status:
  volumes:
  - handle: libvirt-provider.ironcore.dev/ceph/libvirt-provider.ironcore.dev/ceph^xyz
    lastStateTransitionTime: "2024-09-04T11:38:24Z"
    name: root-disk-1
    state: Attached
    volumeRef:
      name: machine-root-disk-1
```

## Motivation

This is a quality of life addition to easily identify the resources claimed by a `Machine` resource.
