### ISSUE TITLE
machine resource Userdata

### ISSUE THREAD

**Issue by gehoern** [ironcore-dev/ironcore#112]
a one dimensional userdata is too flat:

it should be a key value definition e.g 

```
  userData:
    - name: ignition
      value: |
        version: 1.3.0
        ignition:
        config:
          merge:
            - source: http://45.86.152.1/ipxe/passwd.json
            - source: http://45.86.152.1/ipxe/bird.json
            - source: http://45.86.152.1/ipxe/install.json
            - source: http://45.86.152.1/ipxe/utils.json
        storage:
          files:
            - path: /etc/systemd/network/lo.network
              overwrite: yes
              mode: 0644
              contents:
                inline: |
                  [Match]
                  Name=lo

                  [Network]
                  Address=100.64.10.121/32
                  Address=45.86.152.221/32myIgnitionJson
    - name: UEFI
      value: |
        - name: PK
          UUID: 8be4df61-93ca-11d2-aa0d-00e098032b8c
          value: pki.Gardenlinux.io/kernel.crt
```
