### ISSUE TITLE
Additional downward API labels which where configured in poolet deployments are not brokered down properly

### ISSUE THREAD

**Issue by balpert89** [ironcore-dev/ironcore#1171]
When labels are configured in the poolet deployment (e.g. https://github.com/ironcore-dev/ironcore/blob/main/config/machinepoollet-broker/manager/manager.yaml#L34-L36), those labels are not properly brokered down a layer.

The details of a `Machine` show empty fields for the extra downward labels:

```
apiVersion: compute.ironcore.dev/v1alpha1
kind: Machine
metadata:
  annotations:
    machinebroker.ironcore.dev/labels: '{"downward-api.machinepoollet.ironcore.dev/root-machine-name":"","downward-api.machinepoollet.ironcore.dev/root-machine-namespace":"","machinepoollet.ironcore.dev/machine-name":"cba03-controlplane-2-gvf4x","machinepoollet.ironcore.dev/machine-namespace":"cba03","machinepoollet.ironcore.dev/machine-uid":"20bf9267-838f-4bee-ae32-1b740062b874"}'
```

When using multiple layers this creates issues, such as:
- identifying the originating machines is inconvenient
- operating at scale we have seen duplicate machines being created. Using the downward API labels for proper filtering can solve this

**Comment by lukasfrank** [comment]
As in offline discussion, pls try the following configuration: 

top level poollet: 
```
        - name: manager
          args:
            - --machine-downward-api-label=root-machine-namespace=metadata.namespace
            - --machine-downward-api-label=root-machine-name=metadata.name
            - --machine-downward-api-label=root-machine-uid=metadata.uid
        - name: broker
          args:
            - --namespace=machinepoollet-system
            - --broker-downward-api-label=root-machine-namespace=machinepoollet.ironcore.dev/machine-namespace
            - --broker-downward-api-label=root-machine-name=machinepoollet.ironcore.dev/machine-name
            - --broker-downward-api-label=root-machine-uid=machinepoollet.ironcore.dev/machine-uid

```

AZ poollet 
```
        - name: manager
          args:
            - --machine-downward-api-label=root-machine-namespace=metadata.labels['downward-api.machinepoollet.ironcore.dev/root-machine-namespace']
            - --machine-downward-api-label=root-machine-name=metadata.labels['downward-api.machinepoollet.ironcore.dev/root-machine-name']
            - --machine-downward-api-label=root-machine-uid=metadata.labels['downward-api.machinepoollet.ironcore.dev/root-machine-uid']
        - name: broker
          args:
            - --namespace=machinepoollet-system
            - --broker-downward-api-label=root-machine-namespace=machinepoollet.ironcore.dev/machine-namespace
            - --broker-downward-api-label=root-machine-name=machinepoollet.ironcore.dev/machine-name
            - --broker-downward-api-label=root-machine-uid=machinepoollet.ironcore.dev/machine-uid
```
