### ISSUE TITLE
Missing validation for ResourceName in `ResourceQuota` spec

### ISSUE THREAD

**Issue by ushabelgur** [ironcore-dev/ironcore#1259]
**Describe the bug**
No validation for ResourceName in `ResourceQuota` spec

**To Reproduce**
Create ResourceQuota with invalid ResourceName in spec
For eg:

```
apiVersion: core.ironcore.dev/v1alpha1
kind: ResourceQuota
metadata:
  name: resource-quota-test
  namespace: dev-team-onmetal-api
spec:
  hard: # Hard is the mapping of strictly enforced resource limits.
    requests.invalidresource: "4"
```

ResourceQuota is created without any error

**Expected behavior**
ResourceQuota with invalid ResourceName in spec should not be allowed
