### ISSUE TITLE
ReservedIP Controller

### ISSUE THREAD

**Issue by adracus** [ironcore-dev/ironcore#197]
# Summary

The `ReservedIP` reconciler is currently not implemented. It should be possible to reserve an IP
with that controller.

## Basic example

```yaml
apiVersion: network.onmetal.de/v1alpha1
kind: ReservedIP
metadata:
  name: myReservedIP
spec:
  subnet:
    name: subnet-sample
 assignment:
   kind: Machine
   apiGroup: compute.onmetal.de
   name: machine-sample
#status:
#  ip: 1.2.3.4
#  state: Assigned
```

For now, the `assignment` block should be skipped and the resource where an IP is bound to is not required in the status.

An implementation of creating / getting the IP can be found in the `Machine` controller where IPs for the various interfaces are allocated:
https://github.com/onmetal/onmetal-api/blob/ed87541379ca9930946d7c221fdbe4f35b3f5bbe/controllers/compute/machine_controller.go#L90

## Motivation

With the `ReservedIP` type, we can have IPs that are stable across different instances of `Machine`s or use them for `Gateway`s to stably identify network resources.

## Definition of Done

* The `ReservedIP` controller creates a sub-IPAMRange object that allocates the specified or any matching IP
* The reserved IP should be reflected in the status of the `ReservedIP` as well as the `.status.state` should be updated.
* There are tests for the main flow (creation of reserved ip, verifying existence of the `IPAMRange`, verifying the status)
