### ISSUE TITLE
Add volume size also to Volume status

### ISSUE THREAD

**Issue by arttor** [ironcore-dev/ironcore#241]
# Summary

Add size parameter to Volume status indicating the actual resources of the underlying volume. Size parameter in the spec will reflect requested resources.

## Basic example

```yaml
apiVersion: storage.onmetal.de/v1alpha1
kind: Volume
...
status:
  resources:
    storage: 100Gi
```

## Motivation

Api user should know the actual size of the underlying volume. It may be different from requested size during volume resize operation. This can happen if the storage cluster doesn't have enough capacity to fulfill the new size.
