### ISSUE TITLE
Add `Network` type to networking API group

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#364]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add an `Network` type to our API.

## Basic example

```
apiVersion: networking.onmetal.de/v1alpha1
kind: Network
metadata:
  namespace: default
  name: my-network
```

## Definition of done
- `Network` type definition + adding it to the registry
- Basic validation and validation tests
