### ISSUE TITLE
Add `NetworkInterfaceBinding` type to networing API group

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#365]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add an `NetworkInterfaceBinding` type to our API.

## Basic example

```
apiVersion: networking.onmetal.de/v1alpha1
kind: NetworkInterfaceBinding
metadata:
  namespace: default
  name: my-machine-interface
ips:
  - 192.168.178.1
  - 2607:f0d0:1002:51::4
```

## Definition of done
- `NetworkInterfaceBinding` type definition + adding it to the registry
- Basic validation and validation tests
