### ISSUE TITLE
Add `AliasPrefix` type to networking API group

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#366]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add  an `AliasPrefix` type to our API.

## Basic example

```
apiVersion: networking.api.onmetal.de/v1alpha1
kind: AliasPrefix
metadata:
  namespace: default
  name: my-pod-prefix-1
spec:
  networkRef:
    name: my-network
  networkInterfaceSelector:
    matchLabels:
      foo: bar
  prefix:
#    value: 10.0.0.0/24 # It's possible to directly specify the AliasPrefix value
    ephemeralPrefix:
      spec:
        parentRef:
          name: my-pod-prefix
        prefixLength: 24
status:
  prefix: 10.0.0.0/24
```

## Definition of done

- `AliasPrefix` type definition + adding it to the `registry`
- Basic validation and validation tests
