### ISSUE TITLE
Add `VirtualIP` type to networking API group

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#368]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add  an `VirtualIP` type to our API.

## Basic example

```
apiVersion: networking.onmetal.de
kind: VirtualIP
metadata:
  namespace: default
  name: my-virtual-ip
spec:
  type: Public
  ipFamily: IPv4
  networkInterfaceSelector:
    matchLabels:
      foo: bar
status:
  ip: 45.86.152.88
```

## Definition of done

- `VirtualIP` type definition + adding it to the `registry`
- Basic validation and validation tests
