### ISSUE TITLE
Add `VirtualIPRouting` type to networking API group

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#369]
# Summary

As the described in the new networking API proposal https://github.com/onmetal/onmetal-api/blob/docs/proposal/network-integration/docs/proposals/01-networking-integration.md we need to add  an `VirtualIPRouting` type to our API.

## Basic example

```
apiVersion: networking.onmetal.de
kind: VirtualIPRouting
metadata:
  namespace: default
  name: my-virtual-ip
networkRef:
  name: my-network
subsets:
  - targetRef:
      name: my-machine-interface
      uid: 2020dcf9-e030-427e-b0fc-4fec2016e73b
```

## Definition of done

- `VirtualIPRouting` type definition + adding it to the `registry`
- Basic validation and validation tests
