### ISSUE TITLE
SSH key object

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#44]
# Summary

As a user I should be able to define a public SSH key

```yaml
apiVersion: compute.onmetal.de/v1alpha1
kind: SSHPublicKey
metadata:
  name: my-pubkey
  namespace: myscope-2342342
spec:
  sshPublicKey: ssh-rsa jksdlkjadljasldjaldjasljdlasjdl
  description: "my awesome key"
  expirationDate: 03/14/2017
status:
  state: Vailid/Expired
  fingerPrint: 08:92:43:34:32
  keyLength: 2048
  algorithm: RSA/ECDSA ...
  publicKey: kjlkjsldjsaldjsldjlj # PEM encoded public key
```
