### ISSUE TITLE
Image Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#45]
# Summary

```yaml
apiVersion: compute.onmetal.de/v1alpha1
kind: Image
metadata:
  name: ubuntu-latest
  namespace: onmetal
spec:
  # type: standard/firewall/etc. ... move into annotations eventually
  maturity: preview/production
  expirationTime: 
  os: Ubuntu
  version: 20.04
  arch: amd64
  source: 
  - name: ref
    imageName: ubuntu-20.04
  - name: kernel 
    url: https://
    cmdLine: mitigations=off
    hash:
      algorithm: SHA1
      value: lkjl4j5l34j5l43kj534lj5l
  - name: initrd
    url: https://
    hash:
      algorithm: SHA1
      value: lkjl4j5l34j5l43kj534lj5l
  - name: rootfs: 
    url: https://
    hash:
      algorithm: SHA1
      value: lkjl4j5l34j5l43kj534lj5l
status:
  state: Valid
  hashes:
  - name: kernel
    hash: lj4l2kj4l3kj # normalized cache, today SHA3
  - name: initrd
    hash: lkljdlsajdsljda
  regions:
  - name: Frankfurt
    state: Ready # cached and available for direct use
    message: "Ready to consume"
  - name: Tokio
    state: Verified # can be downloaded
    message: "Can be downloaded"
```
