### ISSUE TITLE
Volume Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#46]
# Summary

```yaml
apiVersion: storage.onmetal.de/v1alpha1
kind: Volume
metadata:
  name: myvolume
  namespace: scope-8739274932
spec:
  storageClass: fast-ssd
  storagePool: onmetal/default
  size: 100Gi
status:
 state: Available/Pending/Attached/Error
 message: "All good."
```
