### ISSUE TITLE
Machine Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#50]
# Summary

As a user I want to define a `Machine` resource.

```yaml
apiVersion: compute.onmetal.de/v1alpha1
kind: Machine
metadata:
  name: myMachine
  namespace: scope-8739274932
spec:
  hostname: myhost
  machineClass: x3.xlarge
  # (optional) pool: myReservedVMs
  location:
    region: eu-central
    availabilityZone: f1
  image:
    scope: garden # global
    name: ubuntu
  sshPublicKeys:
  - name: mykey # name or selector
     scope: myScope
     selector: # optional: either selector for current scope or all parent scopes 
        matchLabels:
             username: myuser
  interfaces:
  - subnet: 
       name: mySubnetName
       scope: someScopeNamespace
    #name: eth0
    #ip:
  - reservedIP:
       name: myReservedIP
       scope: myscope
    #name: eth3
  - reservedIP:
      name: mySecondReservedIP
      scope: myscope2
    #name: eth4
  - subnet:
       name: mycompanynet
       scope: accountNamespace
    #name: eth1
    #ip:
  securityGroups:
  - name: mysecgroup1
  - name: mysecgroup2
  volumeClaims:
  - name: rootdisk # first disk is root disk
    retainPolicy: deleteOnTermiante # emphemeral in baremetal case
    device: /dev/sda
    storageClass: slow
    size: 100GB
  - name: tmpDisk
    retainPolicy: deleteOnTermiante
    storageClass: slow
    device: /dev/sdb
    size: 10GB
  - name: data
    retainPolicy: persistant
    storageClass: slow
    device: /dev/sdc
    size: 100GB
  - name: reusedisk
    retainPolicy: persistant # not ephemeral
    device: /dev/sdx
    volume: 
      name: blubbber0234324
      scope: scope-87973947
  userData: |
    myIgnitionJson
status:
  features:
    type: vm
    # (optional)
    # location:
    #   region: Frankfurt
    #   az: f1
    #   account: abcd1234
    vCPU: 4
    cpuClass: standard
    memory: 1GB
    memoryClass: standard
  interfaces:
  - subnet: 
       name: mySubnetName
       scope: someScopeNamespace
    name: eth0
    ip: 1.1.1.1
  - reservedIP:
       name: myReservedIP
       scope: myscope
    name: eth3
    ip: 8.8.8.8
    subnet: 
       name: mySubnetName
       scope: someScopeNamespace
  - reservedIP:
       name: myReservedIP
       scope: myscope
    name: eth3
    ip: 4.4.4.4
    subnet: 
       name: mySubnetName
       scope: someScopeNamespace
  - reservedIP:
       name: myDynamicIP
       scope: myscope
    name: eth5
    ip: 8.8.8.5
    subnet: 
       name: mySubnetName
       scope: someScopeNamespace
  - subnet: 
       name: mySubnetName
       scope: someScopeNamespace
    name: eth0
    ip: 1.1.1.2
  volumes:
  - name: rootdisk
    storagePool:
      name: myStoragePool
      scope: myScope
    device: /dev/sda
  - name: tmpDisk
    storagePool:
      name: myStoragePool
      scope: myScope
    device: /dev/sdd
  volumeAttachments:
  - name: mydisk
    volumeAttachment: myattachment-2
  - name: dynamic/disk123234534
    volumeAttachment: myattachment-2
```
