### ISSUE TITLE
SecurityGroup Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#61]
# Summary

```
apiVersion: network.onmetal.de/v1alpha1
kind: SecurityGroup
metadata:
  name: mySecGroup
  namespace: scope-8739274932
spec:
  ingress:
  - name: webserver # optional
    securityGroupRef:
      name: mySecGroup
      scope: scope-324342
  - name: ssh # optional
    action: allow/deny # allow == default
    protocol: TCP # optional "*" if not set
    portRange: 22 # optional same as protocol
    source:
      cidr: 1.1.1.1/16
      #secGroupRef: # if cidr not set
      #  name: mySecGroup2
      #  scope: scope-1342345345
  egress:
  - name:
    action: allow/deny
    protocol:
    portRange:
    destination:
      cidr: 
      secGroupRef: # if cidr not set
        name: mySecGroup2
        scope: scope-1342345345
status:
  state: Used/Unused/Invalid
  message: "All good"
```
