### ISSUE TITLE
`Gateway` Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#62]
# Summary

```
apiVersion: network.onmetal.de/v1alpha1
kind: Gateway
metadata:
  name: myGateway
  namespace: scope-8739274932
spec:
  region: frankfurt # how should this be mapped for cross region east west subnets
  uplink:
    subnet:
      name: mysubnet
      scope: scope-8745987349578
   reservedIP: # optional 
     name: myIP
     scope: scope-234342
  SNAT: true # false
  eastWest:
  - name: mySubnet1
     scope: scope-234234
  - name: mySubnet2
     scope: scope-897392
status:
  state: Up/Down/Invalid
  message: "All good"
  ip: 1.1.1.1
```
