### ISSUE TITLE
`Subnet` Resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#63]
# Summary

```
apiVersion: network.onmetal.de/v1alpha1
kind: Subnet
metadata:
  name: mySubnet
  namespace: scope-8739274932
spec:
  parentSubnet:
    name: mySubnet1
    scope: scope-3424233
  locations: # optional
    - regions: frankfurt
       availabilitzZones:
       - az1
       - az2
  ranges:
  - cidr: 1.1.1.1/12
    blockedRanges:
    - 1.1.1.1/24
  - cidr: 2.2.2.2/12
  # size: "/12" # derived from the parent subnet - future settings
  # or capacity: 12 == 12 ip addresses from parent subnet 
status:
  state: Up/Down/Invalid
  message: "All good"
```
