### ISSUE TITLE
SubnetIP resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#67]
# Summary

```
apiVersion: network.onmetal.de/v1alpha1
kind: SubnetIP
metadata:
  name: mySubnetIP
  namespace: scope-8739274932
spec:
  ip: 1.1.1.1
  subnet:
    name: mySubnet
    scope: scope-43534543
  target:
    kind: Machine
    apiGroup: compute.onmetal.de
    name: myVM2
    scope: scope-234243
status:
  state: Assigned/Unassigned/Invalid
  message: "All good"
```
