### ISSUE TITLE
`Network` resource

### ISSUE THREAD

**Issue by afritzler** [ironcore-dev/ironcore#79]
# Summary

```
apiVersion: network.onmetal.de/v1alpha1
kind: Network
metadata:
  name: myNetwork
  namespace: scope-8739274932
spec:
  description: "My awesome network"
status:
  state: Up/Down/Invalid
  message: "All good"
```
